CREATE TABLE COMUNA(
	ID INT NOT NULL,
	NOMBRE VARCHAR(50),
	CONSTRAINT COMUNA_PK PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
	RUT INT NOT NULL,
	NOMBRE VARCHAR(5),
	COMUNA_ID INT NOT NULL,
	CONSTRAINT CLIENTE_PK PRIMARY KEY(RUT),
	CONSTRAINT COMUNA_FK FOREIGN KEY(COMUNA_ID)
	REFERENCES COMUNA(ID)
);
