//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.ServiceProductoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProductoReference.IServiceProducto")]
    public interface IServiceProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/agregarProducto", ReplyAction="http://tempuri.org/IServiceProducto/agregarProductoResponse")]
        bool agregarProducto(int codigo, string nombre, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/agregarProducto", ReplyAction="http://tempuri.org/IServiceProducto/agregarProductoResponse")]
        System.Threading.Tasks.Task<bool> agregarProductoAsync(int codigo, string nombre, int valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductoChannel : Tienda.ServiceProductoReference.IServiceProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<Tienda.ServiceProductoReference.IServiceProducto>, Tienda.ServiceProductoReference.IServiceProducto {
        
        public ServiceProductoClient() {
        }
        
        public ServiceProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool agregarProducto(int codigo, string nombre, int valor) {
            return base.Channel.agregarProducto(codigo, nombre, valor);
        }
        
        public System.Threading.Tasks.Task<bool> agregarProductoAsync(int codigo, string nombre, int valor) {
            return base.Channel.agregarProductoAsync(codigo, nombre, valor);
        }
    }
}
